language: node_js
node_js:
  - '0.12'
  - 'iojs'
script: npm run ci
addons:
  sauce_connect: true
env:
  global:
    - secure: X1j71RBXBPYZddTay9z2+gyrbMsBUv7K4MvX4n1a2nyxZUHS8xNxZtI39g9sxIKeULVGFe/Y6g39pOlyNsJtecE6zDgogQQT3wFSb/ljP2nP+XNq6Gg6cxSf0pG/Ce7NFR0IbO9WDiWxxw9qfjsojuxrY0dqH3798ET62KN5Mo7QVl+olzimLK87397s86e6DpBiuE/+pmkGB+ey5RO5kxI8BMp5hnoRnJjRWlF+rwitRBLrhErk68sSImm+aGuMTJWKla2xhtdQkMB04Y7HEzCCbePSt1excuuPbZhO9gCYiQQ5n5A+pkJYsd4G8wAKz/CqzKm3BQJhRPE3ZedgervwtGnhMvpIl1axe/xd2jkxrOTIIK1FAFaa1fps+/4SINazohw2p+9R8ZhquZ3H2D/4HA7KD2B0/UhvJ+weaRs0QbDT7VfNgw4WlUkZL5TdDSwsM8NljWB8Os5s2SZufTTjb/4pu/7XGnLViAkosICY3gvLTTUwyxOzRuJ+t5nobkJMeig/zrsukd+joFlPUDQjUXEbQh4dQyo/472DFrRUjdDD+xRHMi4fXEbyCBnbHZM9wkGBO6iJXk1s7shIBZ4g4lv4Ku8v71B97c13kEVi1MaGnRqsRPLm1jjs1rRoT+GBGBhp5z6xC2WqS4pboE/L/VAAnCmlJIQP7Rdq0D8=
    - secure: YZKtqy+2yGZFv0rWoUqVVOFHRXOXaNHMDYFexrhkkXBfTFocxByp8p+5ncVDPN+jVxSpCprUQMLtWSglvy5iVFHldkeHy6OGZ/aD226/xsFkC1gX8/PsnjrESWVRCLiNly7l6xozMAXemf8FUNKwhazv2htxT7jxiNk3z+bXioKQSgg6vh82isZDQj/P4piZM3uEpbs4wV749gK84QbJD1xbrs0MYtblFODVSiC1apX5qIlGh8+ZEV9En2FZ93kiqMyWwLeZdcep4/P6zCHUbGCIeUahg+3bdCCDXOaIBYH5AouVEi/AzxUJe7kxB1UIcDOKFPleucqNEmM8JVb/2ptUMvDZvp2hSOm4AkjuDeMpTtVL/0bBXk8KOt8FrfkytdlYniSCgIbTN7hzKUUZF4E9HNwFCKBUO3zE92ub8PQ0lKRbe9uKUF51vxq9vn2vj1Ebb+X3nTB02y4O96Fm2JDbkaKgHMK+1XK7Tjo4cR3giFk1b5eVmDkO4/HE2bc3g1Uq8sv4mBNopOs6US0pXZ9XiQL1KmudYt5xuT9TD9qrBz+DO+DMlW4Eh/3FQVBHyptPuZiWac90C9FetKyotdwd5hEpv/LQOcXbDonyYlwUPIOwKs1d8Xf32YPLBBiNplM90ffu/3fIo5MySllMnCn+yFrwDurqjFJJugZ+AEA=

